"""applicationModelFix

Revision ID: 00effe15d8c3
Revises: 9d6b1f2a3c4d
Create Date: 2026-04-26 14:57:51.686410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00effe15d8c3'
down_revision: Union[str, Sequence[str], None] = '9d6b1f2a3c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'first_name')
    op.drop_column('applications', 'email')
    op.drop_column('applications', 'phone')
    op.drop_column('applications', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('email', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.add_column('applications', sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
