"""add psychologist statuses table

Revision ID: 065e485b58c3
Revises: c8f9e0a1b2c3
Create Date: 2026-09-20 21:13:38.694703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065e485b58c3'
down_revision: Union[str, Sequence[str], None] = 'c8f9e0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psychologist_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pid', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('vacation', 'sick', name='psychologist_status_enum'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pid'], ['psychologists.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychologist_statuses_pid'), 'psychologist_statuses', ['pid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychologist_statuses_pid'), table_name='psychologist_statuses')
    op.drop_table('psychologist_statuses')
    # ### end Alembic commands ###
