"""make email required and delete users with null email

Revision ID: 23020d3e0038
Revises: combined_rbac_improvements
Create Date: 2025-11-17 18:46:33.151474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23020d3e0038'
down_revision: Union[str, Sequence[str], None] = 'combined_rbac_improvements'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete all users with null email before making the column NOT NULL
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM users WHERE email IS NULL"))
    
    # Now make email column NOT NULL
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
