"""fix dates and add event_date

Revision ID: 4ad174116c62
Revises: 0465de7813f5
Create Date: 2026-05-08 20:43:16.903311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ad174116c62'
down_revision: Union[str, Sequence[str], None] = '0465de7813f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _column_names(bind: sa.Connection, table: str) -> set[str]:
    return {c["name"] for c in sa_inspect(bind).get_columns(table)}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Table/index may be absent on DBs that never had b2c3d4e5f6a7 audit logs.
    op.drop_table("application_audit_logs", if_exists=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    bind = op.get_bind()
    if "conclusion" not in _column_names(bind, "appointments"):
        op.add_column(
            "appointments",
            sa.Column(
                "conclusion",
                sa.String(length=2048),
                nullable=True,
                comment="Заключение психолога",
            ),
        )
    if "event_date" not in _column_names(bind, "news"):
        op.add_column(
            "news",
            sa.Column(
                "event_date",
                sa.DateTime(timezone=True),
                nullable=True,
                comment="Дата мероприятия",
            ),
        )
        op.execute(
            sa.text('UPDATE news SET event_date = COALESCE("date", now()) WHERE event_date IS NULL')
        )
        op.alter_column(
            "news",
            "event_date",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
            existing_comment="Дата мероприятия",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news", "event_date", if_exists=True)
    op.drop_column("appointments", "conclusion", if_exists=True)
    op.alter_column('applications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('application_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('application_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('previous_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('new_status', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('actor_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('application_audit_logs_application_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_application_audit_logs_application_id'), 'application_audit_logs', ['application_id'], unique=False)
    # ### end Alembic commands ###
