"""add scheduled_time and comment to appointments

Revision ID: 511f738f16f7
Revises: d789ac864327
Create Date: 2025-10-25 20:18:04.225888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '511f738f16f7'
down_revision: Union[str, Sequence[str], None] = 'd789ac864327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('scheduled_time', sa.DateTime(), nullable=False, comment='Время назначенной встречи'))
    op.add_column('appointments', sa.Column('comment', sa.String(length=512), nullable=True, comment='Комментарий к записи'))
    op.alter_column('appointments', 'remind_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Время напоминания',
               existing_nullable=True)
    op.alter_column('appointments', 'last_change_time',
               existing_type=postgresql.TIMESTAMP(),
               comment='Время последнего изменения',
               existing_nullable=False)
    op.alter_column('appointments', 'venue',
               existing_type=sa.VARCHAR(length=128),
               comment='Место проведения встречи',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'venue',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Место проведения встречи',
               existing_nullable=False)
    op.alter_column('appointments', 'last_change_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Время последнего изменения',
               existing_nullable=False)
    op.alter_column('appointments', 'remind_time',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Время напоминания',
               existing_nullable=True)
    op.drop_column('appointments', 'comment')
    op.drop_column('appointments', 'scheduled_time')
    # ### end Alembic commands ###
