"""separate_theparis_pk

Revision ID: 6090345cb216
Revises: 511f738f16f7
Create Date: 2025-10-26 19:47:38.508364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6090345cb216'
down_revision: Union[str, Sequence[str], None] = '511f738f16f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('therapists', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_therapists_id'), 'therapists', ['id'], unique=False)
    op.create_index(op.f('ix_therapists_user_id'), 'therapists', ['user_id'], unique=True)
    op.drop_constraint(op.f('therapists_id_fkey'), 'therapists', type_='foreignkey')
    op.create_foreign_key(None, 'therapists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'therapists', type_='foreignkey')
    op.create_foreign_key(op.f('therapists_id_fkey'), 'therapists', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_therapists_user_id'), table_name='therapists')
    op.drop_index(op.f('ix_therapists_id'), table_name='therapists')
    op.drop_column('therapists', 'user_id')
    # ### end Alembic commands ###
