"""appointment_delete_initials

Revision ID: 699807fe3788
Revises: 00effe15d8c3
Create Date: 2026-04-26 16:30:39.688218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '699807fe3788'
down_revision: Union[str, Sequence[str], None] = '00effe15d8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'patient_first_name')
    op.drop_column('appointments', 'patient_last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('patient_last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('patient_first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
