"""create psy_tests table

Revision ID: 76ea597063ce
Revises: c8f9e0a1b2c3
Create Date: 2026-09-20 15:47:15.568687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '76ea597063ce'
down_revision: Union[str, Sequence[str], None] = 'c8f9e0a1b2c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

test_type_enum = postgresql.ENUM('ENTERTAINING', 'MEDICAL', name='testtype', create_type=False)


def upgrade() -> None:

    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    test_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('psychological_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Название теста'),
    sa.Column('description', sa.Text(), nullable=False, comment='Описание теста'),
    sa.Column('type', test_type_enum, nullable=False, comment='Тип теста: мед или развл'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychological_tests_id'), 'psychological_tests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psychological_tests_id'), table_name='psychological_tests')
    op.drop_table('psychological_tests')

    test_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

